# Generated by Django 5.2.8 on 2025-11-30 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='seniority',
            field=models.CharField(choices=[('jr', 'Junior'), ('pl', 'Pleno'), ('sr', 'Senior')], max_length=2),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_article_slug_per_user'),
        ),
    ]
