# Generated by Django 5.2.8 on 2025-11-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_slug_alter_developer_seniority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='seniority',
            field=models.CharField(choices=[('jr', 'Jr'), ('pl', 'Pl'), ('sr', 'Sr')], max_length=2),
        ),
    ]
